site_name: Sim Gamer Kit
theme:
  name: material

nav:
  - Home: index.md
  - FFFSake:
    - Overview: fffsake/index.md
    - Setup (R14+): fffsake/setup_r14.md
    - Configuration Options: fffsake/options.md
    - vJoy Configuration: fffsake/vjoy_configuration.md
  - IndirectInput: indirect_input/index.md
  - Gremlin Plugins:
    - H-Shifter: joystick_gremlin_plugins/h_shifter.md
    - Handbrake: joystick_gremlin_plugins/handbrake.md
  - Game Guides: game_guides/index.md
  - Hardware Guides: hardware_guides/index.md

markdown_extensions:
  - attr_list
